server:
  port: 8082

spring:
  application:
    name: course-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "0504"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kerimlifatime417@gmail.com
    password: vwunlasnvnaganyc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  config:
    student-url: http://localhost:8081/api

  # JwtService.java faylının oxuması üçün lazım olan hissə:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 30000  # 30 saniyə (ms)
      refresh-token:
        expiration: 604800000 # 7 gün (ms)

logging:
  file:
    name: logs/course-service.log
  level:
    com:
      woofly:
        courseservice: INFO
    org:
      springframework:
        web: DEBUG