server:
  port: 8082

spring:
  application:
    name: course-service

  # --- Verilənlər Bazasının Konfiqurasiyası (PostgreSQL) ---
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "0504"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

  # --- Mail Konfiqurasiyası ---
  mail:
    host: smtp.gmail.com
    port: 587
    username: kerimlifatime417@gmail.com
    password: vwunlasnvnaganyc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # ---  REDIS VƏ KEŞLƏMƏ (CACHING) KONFİQURASİYASI (Düzgün Yerləşdirmə) ---
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms

    cache:
      type: redis
      # TTL-i saniyə olaraq xüsusi parametrdə saxlayırıq
      ttl-seconds: 60
      #ttl-minutes: 1
      #ttl: 7d


# --- Xüsusi Tətbiq Konfiqurasiyaları ---
application:
  config:
    student-url: http://localhost:8081/api

  # JWT Təhlükəsizlik Konfiqurasiyası
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 30000
      refresh-token:
        expiration: 604800000

# --- Loglama Konfiqurasiyası ---
logging:
  file:
    name: logs/course-service.log
  level:
    com:
      woofly:
        courseservice: INFO
    org:
      springframework:
        web: DEBUG